### ISSUE TITLE
Background color fix

### ISSUE THREAD

**Issue by Lukeuke** [BigBrain-Solutions/bbs_website#1]
Add to ``src/index.css`` this line:

```css
html {
  background-color: rgb(51, 65, 85);
}
```

I figured out that the ``<body>`` element will scale out when the content of it will be bigger
